### ISSUE TITLE
这个到底怎么编辑的？请教下

### ISSUE THREAD

**Issue by xinzhongyouhai** [recitativonika/blockless-bless-network-bot#10]
module.exports = [
    {
        usertoken: 'usertoken1',
        nodes: [
            { nodeId: '12D3KooWPvvxpFfdTkw2m2keuw5nUeTRaozWQsREGgetSXbWCdmA', hardwareId: 'bb1d76e9193f7cf2d4f225dc52f1da0c67ee9b8bc0431c0a48ae42c8e9a178a8', proxy: 'http://aaa:sss@46.257.57.174:6581' },
            { nodeId: 'nodeid(pubkey)2', hardwareId: 'hardwareid2', proxy: 'proxy2' },
            { nodeId: 'nodeid(pubkey)3', hardwareId: 'hardwareid3', proxy: 'proxy3' },
            { nodeId: 'nodeid(pubkey)4', hardwareId: 'hardwareid4', proxy: 'proxy4' },
            { nodeId: 'nodeid(pubkey)5', hardwareId: 'hardwareid5', proxy: 'proxy5' }
        ]
    },
    {
        usertoken: 'usertoken2',
        nodes: [
            { nodeId: 'nodeid(pubkey)6', hardwareId: 'hardwareid6', proxy: 'proxy6' }
        ]
    }
    // Add more usertokens as needed
];
这样就行了？？？
            { nodeId: 'nodeid(pubkey)2', hardwareId: 'hardwareid2', proxy: 'proxy2' },
            { nodeId: 'nodeid(pubkey)3', hardwareId: 'hardwareid3', proxy: 'proxy3' },
            { nodeId: 'nodeid(pubkey)4', hardwareId: 'hardwareid4', proxy: 'proxy4' },
            { nodeId: 'nodeid(pubkey)5', hardwareId: 'hardwareid5', proxy: 'proxy5' }这部分是干嘛的~请教下

**Comment by recitativonika** [comment]
If you only use one nodeid, just delete other part. Like this

module.exports = [
    {
        usertoken: 'usertoken1',
        nodes: [
            { nodeId: 'nodeid1', hardwareId: 'hardwareid1', proxy: 'proxy1' }
        ]
    }
];

**Comment by ptiforka** [comment]
Hey @recitativonika 
Thanks for your work

Just curious how I can get a couple of node IDs and hardware IDs? 
as I understood for one installed extension in 1 nodeId and hardwareId? 

What is the way to extend it up to 5 farms on one account?

Thanks for your response in the future :)

**Comment by recitativonika** [comment]
You can login to your account in different browser and device, it will generate different nodeid and hardwareid for each device

or

I make a simple script to generate random `nodeid` and `hardwareid` in this repo, you can use the `gen.js` to do that
```
node gen.js
```
But keep in mind, I made the script for only testing. do with your own risk when you want to use this.
