### ISSUE TITLE
it will stop logging and no more logs

### ISSUE THREAD

**Issue by wuxin-hun** [recitativonika/blockless-bless-network-bot#11]
<img width="900" alt="stop" src="https://github.com/user-attachments/assets/a78abc3e-f87b-4e88-a892-38d0e6d22b4b">

maybe my network is not stable,but i wanna it will skill the error and keep farming,but in fact ,it stop logging and no more logs,i do not know what happens.

**Comment by wuxin-hun** [comment]
![Uploading 222.png…]()

**Comment by recitativonika** [comment]
What do you mean is the script is stop processing? 
have you tried letting the script run for a while?

**Comment by wuxin-hun** [comment]
> 脚本停止处理是什么意思？ 您是否尝试过让脚本运行一段时间？-----------谷歌翻译----------脚本停止运行是什么意思？您是否尝试过让脚本运行一段时间？

log no longer  print ,and i close it late.  let me try it age and tell u later.

**Comment by wuxin-hun** [comment]
what i also wander is that if i generate a new hardware and new publicKey, i should change hardwareId only or change hardwareId and publicKey both?

**Comment by recitativonika** [comment]
> > 脚本停止处理是什么意思？ 您是否尝试过让脚本运行一段时间？-----------谷歌翻译----------脚本停止运行是什么意思？您是否尝试过让脚本运行一段时间？
> 
> log no longer print ,and i close it late. let me try it age and tell u later.

okay, let me know next

**Comment by recitativonika** [comment]
> what i also wander is that if i generate a new hardware and new publicKey, i should change hardwareId only or change hardwareId and publicKey both?

I recomended to use `one nodeid with one hardwareid`, don't use same hardwareid. It might be detected as multi-account by bless network if you use same hardwareid

**Comment by wuxin-hun** [comment]
i try wait it  and it go on farming in my webstorm IDE ,but when when i run .bat in my windows system it will stop for a long time and no longer keep on longging again but i do not know if it real keep farming  ,so i decide to run it in webstorm.  thx
