### ISSUE TITLE
Can multiple proxies run on 1 usertoken?

### ISSUE THREAD

**Issue by lenhu96** [recitativonika/blockless-bless-network-bot#12]
I have a question: if a userToken has one nodeId and one hardwareId, can it run multiple proxies? Will it receive multiple rewards?
Or can each userToken, nodeId, and hardwareId only run on one proxy?

Thanks for reading. I look forward to your reply.

**Comment by recitativonika** [comment]
1 nodeid is only 1 process, so you can't run 1 nodeid with multiple proxies.

**Comment by recitativonika** [comment]
You only need one usertoken for one account, each time you login in the browser or elsewhere will have a different usertoken, just copy one. For nodeid, each extension installation will have a different nodeid and hardwareid comes from the hardware identification of your device, you will need to install in different device to have different hardwareid.

**Comment by lenhu96** [comment]
I got it
Awesome
Thanks for sharing
Love you <3
