### ISSUE TITLE
"cannot find module "https-proxy-agent"  "

### ISSUE THREAD

**Issue by GabSanPro** [recitativonika/blockless-bless-network-bot#14]
solution?

**Comment by recitativonika** [comment]
do you already run `npm install`?

**Comment by GabSanPro** [comment]
sorry i dont close the issue, was exactly that..
i miss to install npm on the bot folder

**Comment by recitativonika** [comment]
Sorry I don't understand what you are saying. Could you explain it again?

**Comment by recitativonika** [comment]
if you mean is you don't know what to use `npm install` , you need to do in the script folder

![image](https://github.com/user-attachments/assets/64c81788-f0e0-4896-9dc8-c9aa3b1c47c2)
