### ISSUE TITLE
How could you handle the JWT token expiry

### ISSUE THREAD

**Issue by tructhienbui** [recitativonika/blockless-bless-network-bot#15]
The current userToken is actual jwt token, which is short live, you can use https://jwt.ms/ to check. How could you handle the JWT token expiry?

**Comment by recitativonika** [comment]
For some reason, their tokens are always valid even when expired and never require new tokens (unlike Dawn Validator which requires new tokens when expired). As to why this happens, IDK.

**Comment by tructhienbui** [comment]
Nice, thnks! You dont mine i made a PR to change from fetch to axois? Which has better handle for custom user-agent, headers...

**Comment by recitativonika** [comment]
Sure
