### ISSUE TITLE
How to get multiple Pubkey and hardware id without switching to other pc?

### ISSUE THREAD

**Issue by scindo07** [recitativonika/blockless-bless-network-bot#16]
Thank you for answering!

**Comment by recitativonika** [comment]
IWhile I don't recommend it, you can use the gen.js script
```bash
node gen.js
```

**Comment by scindo07** [comment]
about gen.js script, do I need proxies for it or nah

**Comment by recitativonika** [comment]
You don't need, that script will generate you NodeID and HWID locally without connection needed.

**Comment by scindo07** [comment]
oh alright, thanks
