### ISSUE TITLE
new PING?

### ISSUE THREAD

**Issue by 20dec** [recitativonika/blockless-bless-network-bot#17]
Hi,

I see new PING API from BLESS. Do you review it?

**Comment by recitativonika** [comment]
Thanks for the heads up, I'll check it out later.

**Comment by 20dec** [comment]
Seem they removed hw ID from node too.

**Comment by recitativonika** [comment]
i can confirm they change the IPfetch and ping data send.
For HWID, they still send this but in the newer version they gather exact hardwareinfo too (cpu models, gpu models, ram, core, etc.)

I will update later when I have time!

**Comment by recitativonika** [comment]
I update the script with the new node logic, please pull the repo again

**Comment by 20dec** [comment]
> I can confirm they change the IPfetch and nodedata send. For HWID, they still send this but in the newer version they gather exact hardwareinfo too (cpu models, gpu models, ram, core, etc.)
> 
> I will update later when I have time!

then now they collect and know all node run via script in same PC hardware. before hw id from the hardware which node created.

**Comment by recitativonika** [comment]
Update the script please, I already add hardwareinfo generator in the script. It automatically generate random hardwareinfo and save it in the .json file. Now the script will send same package payload like the extension do

**Comment by 20dec** [comment]
Thank you for updating. Just one question.
I see in API https://gateway-run.bls.dev/api/v1/nodes/{node}/ping
have payload: {"isB7SConnected":false}

This is the new one i want to tell you, but seem you still use the current old ping in script.

**Comment by recitativonika** [comment]
they still use the old one to ping too. Maybe I'll check again later, right now I don't have much time to make changes to the code.
