### ISSUE TITLE
error body used already

### ISSUE THREAD

**Issue by FxFurEN** [recitativonika/blockless-bless-network-bot#19]
![image](https://github.com/user-attachments/assets/deec78e2-9245-4bec-877d-6b9991f078f6)

**Comment by ZaryImortal** [comment]
Are you trying to use 1 IP for multiple accounts?

**Comment by recitativonika** [comment]
I already update it, pull the repo again!

**Comment by FxFurEN** [comment]
> Are you trying to use 1 IP for multiple accounts?

im using this for a test
