### ISSUE TITLE
I use the id generated by gen.js, and now all 500 errors are reported when making requests. Yesterday it was OK

### ISSUE THREAD

**Issue by tahitimoon** [recitativonika/blockless-bless-network-bot#20]
I use the id generated by gen.js, and now all 500 errors are reported when making requests. Yesterday it was OK

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/ff71d7c0-5ffb-4c84-a99d-38d120a697dc" />

**Comment by recitativonika** [comment]
they now forcing to make new node and must use nodeid that registered by extension.
you need delete and retire all from dashboard and use nodeid from extension instead, for HWID you can still use the gen.js for generate that

**Comment by surendra841** [comment]
So we need to register a new nodeid using chrome extension. How many nodes are working per account now?
@recitativonika

**Comment by recitativonika** [comment]
5 nodeid per account

**Comment by surendra841** [comment]
@recitativonika Have to register 5 nodes in the extension right?

**Comment by recitativonika** [comment]
> @recitativonika Have to register 5 nodes in the extension right?

you can run 1-5 nodes
