### ISSUE TITLE
Sciprt Doesnt work anymore?

### ISSUE THREAD

**Issue by surendra841** [recitativonika/blockless-bless-network-bot#21]

**Comment by surendra841** [comment]
![image](https://github.com/user-attachments/assets/4220b651-26b4-4113-9df7-86385ca0b564)
![image](https://github.com/user-attachments/assets/2e0e4f87-2493-4caa-bd1c-fc82677165b1)

**Comment by recitativonika** [comment]
[check here](https://github.com/recitativonika/blockless-bless-network-bot/issues/20#issuecomment-2560981519)
