### ISSUE TITLE
Node registration failed

### ISSUE THREAD

**Issue by Zcb991** [recitativonika/blockless-bless-network-bot#23]
[[2024-12-28 13:45:07]] Node registration completed for nodeId: 12D3KooWkMl833QtKj2c2vl3DANJO9D1GpPrTwEAmY9CmLzxejtp. Response: {
  statusCode: 500,
  error: 'Internal Server Error',
  message: 'Invalid peer ID [Register]: 12D3KooWkMl833QtKj2c2vl3DANJO9D1GpPrTwEAmY9CmLzxejtp'
}

![image](https://github.com/user-attachments/assets/a54ba081-8b2c-4338-a9e6-c3d03adbb374)

what happened ?

**Comment by recitativonika** [comment]
https://github.com/recitativonika/blockless-bless-network-bot/issues/20#issuecomment-2560981519

**Comment by Zcb991** [comment]
> [#20 (comment)](https://github.com/recitativonika/blockless-bless-network-bot/issues/20#issuecomment-2560981519)

Thank you, but I found the way how to generate right hardwareId and nodeId by script.

**Comment by dieutx** [comment]
> > [#20 (comment)](https://github.com/recitativonika/blockless-bless-network-bot/issues/20#issuecomment-2560981519)
> 
> Thank you, but I found the way how to generate right hardwareId and nodeId by script.

could you please share it? many thanks

**Comment by recitativonika** [comment]
> > > [#20 (comment)](https://github.com/recitativonika/blockless-bless-network-bot/issues/20#issuecomment-2560981519)
> > 
> > 
> > Thank you, but I found the way how to generate right hardwareId and nodeId by script.
> 
> could you please share it? many thanks

it already in the repo, use `node gen.js` and choose generate pure hardwareid
