### ISSUE TITLE
Position B7S_AUTH_TOKEN 

### ISSUE THREAD

**Issue by rezzachuky2** [recitativonika/blockless-bless-network-bot#5]
bang posisi B7S_AUTH_TOKEN dimana ya barusan pake console tab dan check distorage application,,, kosong..

**Comment by recitativonika** [comment]
you must already logged in and in the dashboard to get the token, please read it again slowly

**Comment by rezzachuky2** [comment]
> you must already logged in and in the dashboard to get the token, please read it again slowly

thanks
