### ISSUE TITLE
Request PAID version

### ISSUE THREAD

**Issue by superit63** [recitativonika/blockless-bless-network-bot#9]
Hi,
Thanks a lot for your code, its amazing; however, It will be great if you can add more function like: creating account and input mail:pass instead of inputing token, nodeid, hardwareid....
Do you have any group or community channel? I will join and contribute in anyway.
I am happy if you have paid version or even donation for your work.

My telegram: @holdtodie93
Happy to connect to you
Thanks.

**Comment by recitativonika** [comment]
Thanks for the great feedback and requests, but it probably won't be my top priority to implement that feature since I code only when I have free time.
